import whisper  # OpenAI의 Whisper 음성 인식 라이브러리를 가져옵니다.
import cv2  # 영상 분석 및 FPS 추출을 위한 OpenCV 라이브러리를 가져옵니다.
import json  # 데이터를 구조화된 JSON 파일로 저장하기 위해 불러옵니다.
import pandas as pd  # 데이터를 표 형태의 CSV 파일로 저장하기 위해 불러옵니다.
import os  # 폴더 생성 및 경로 존재 여부 체크 등 시스템 환경 처리를 위해 불러옵니다.


def get_video_fps(video_path):  # 비디오의 FPS를 안전하게 추출하는 보조 함수입니다.
    cap = cv2.VideoCapture(video_path)  # 영상 파일을 열어 캡처 객체를 생성합니다.
    if not cap.isOpened():  # 비디오 파일이 정상적으로 열리지 않았는지 확인합니다.
        return 0.0  # 파일에 문제가 있다면 예외 처리를 위해 0.0을 반환합니다.
    fps = cap.get(cv2.CAP_PROP_FPS)  # OpenCV 속성 기능을 이용해 영상의 FPS를 가져옵니다.
    cap.release()  # 메모리 관리를 위해 사용이 끝난 캡처 객체를 해제합니다.
    return fps  # 획득한 FPS 소수점 값을 최종 반환합니다.


def format_ass_time(seconds):  # 초 단위를 ASS 자막 포맷(H:MM:SS.cs)으로 변환합니다.
    hours = int(seconds // 3600)  # 전체 초에서 시 단위를 계산해 정수로 만듭니다.
    minutes = int((seconds % 3600) // 60)  # 남은 시간에서 분 단위를 계산해 정수로 만듭니다.
    secs = int(seconds % 60)  # 최종 남은 초 단위를 정수로 계산합니다.
    centisecs = int(
        round((seconds - int(seconds)) * 100)
    )  # 소수점 아래 초를 1/100초 단위인 센티초로 바꿉니다.
    return f"{hours}:{minutes:02d}:{secs:02d}.{centisecs:02d}"  # 포맷에 맞춘 문자열을 생성하여 반환합니다.


def generate_short_subtitle_files(
    video_path, output_dir, model_size="turbo"
):  # 문장을 짧게 쪼개어 자막을 만드는 고제어형 함수입니다.
    if not os.path.exists(
        video_path
    ):  # 입력한 비디오 파일 경로가 유효한지 체크합니다.
        print(
            f"오류: '{video_path}' 파일 없음"
        )  # 파일이 없는 경우 경고 메시지를 출력합니다.
        return  # 비정상적인 흐름을 방지하기 위해 함수를 즉시 종료합니다.
    if not os.path.exists(
        output_dir
    ):  # 저장할 출력 폴더가 현재 경로에 존재하는지 체크합니다.
        os.makedirs(
            output_dir
        )  # 존재하지 않는다면 하위 폴더까지 포함해 안전하게 생성합니다.
    base_name = os.path.splitext(os.path.basename(video_path))[
        0
    ]  # 파일의 확장자를 떼어내고 순수 파일 이름만 추출합니다.
    json_path = os.path.join(
        output_dir, f"{base_name}_subtitles.json"
    )  # 결과물을 저장할 JSON 파일 경로를 조합합니다.
    csv_path = os.path.join(
        output_dir, f"{base_name}_subtitles.csv"
    )  # 결과물을 저장할 CSV 파일 경로를 조합합니다.
    ass_path = os.path.join(
        output_dir, f"{base_name}_subtitles.ass"
    )  # 결과물을 저장할 ASS 파일 경로를 조합합니다.
    fps = get_video_fps(
        video_path
    )  # 앞서 정의한 보조 함수로 원본 영상의 FPS를 가져옵니다.
    print(
        f"🤖 Whisper '{model_size}' 모델 로드 중..."
    )  # 짧은 문장 판단력 향상을 위해 고성능 모델을 준비합니다.
    model = whisper.load_model(
        model_size
    )  # 지정된 크기의 Whisper 모델을 메모리에 로드합니다.
    kor_prompt = "안녕하세요. 짧은 문장 위주로 가독성 있게 띄어쓰기를 지켜서 전사해 주세요."  # 짧은 호흡의 분할을 유도하는 힌트 프롬프트입니다.
    print(
        "🗣️ 문장 쪼개기(Short Segmentation) 옵션을 적용하여 STT를 시작합니다..."
    )  # 제어 옵션이 가동됨을 출력합니다.
    result = model.transcribe(  # 문장 길이를 타이트하게 제어하기 위한 특수 옵션들을 주어 전사를 실행합니다.
        video_path,  # 분석 대상이 되는 비디오 미디어 파일의 경로를 인자로 넘깁니다.
        language="ko",  # 다국어 판단 혼선을 방지하기 위해 언어를 한국어로 명시합니다.
        initial_prompt=kor_prompt,  # 초기 프롬프트를 주입하여 짧은 텍스트 생성을 자연스럽게 유도합니다.
        temperature=0.0,  # 무작위성을 배제하여 가장 확실하고 정확하게 끊어지는 지점을 채택합니다.
        word_timestamps=True,  # [핵심] 단어/구절 단위의 세밀한 시간 타임스탬프 기능을 강제로 활성화합니다.
        no_speech_threshold=0.6,  # 음성이 없는 묵음 구간을 더 민감하게 감지하여 자막을 강제로 분리합니다.
        condition_on_previous_text=False,  # 이전 문맥을 과도하게 이어 붙이려는 성질을 차단하여 문장이 길어지는 것을 막습니다.
    )  # 인식이 완료되면 짧게 쪼개진 세그먼트 데이터가 담긴 결과 딕셔너리가 반환됩니다.
    subtitle_data = (
        []
    )  # 최종 파일들로 가공하기 위해 정제된 데이터를 담을 리스트를 생성합니다.
    for segment in result[
        "segments"
    ]:  # 모델이 촘촘하게 분할해 준 문장 단위 조각들을 하나씩 꺼내며 순회합니다.
        subtitle_data.append(
            {  # 정제된 시간 정보와 텍스트를 딕셔너리 구조로 결합하여 저장합니다.
                "start_time": round(
                    segment["start"], 3
                ),  # 자막 시작 시간을 소수점 셋째 자리까지 반올림합니다.
                "end_time": round(
                    segment["end"], 3
                ),  # 자막 종료 시간을 소수점 셋째 자리까지 반올림합니다.
                "fps": round(
                    fps, 2
                ),  # 추출해 둔 영상 FPS 정보를 소수점 둘째 자리까지 기록합니다.
                "text": segment["text"].strip(),  # 불필요한 앞뒤 공백 문자를 깨끗이 제거한 자막 텍스트입니다.
            }
        )  # 데이터 축적 단계를 마무리합니다.
    with open(
        json_path, "w", encoding="utf-8"
    ) as f:  # 유니코드 저장을 위해 utf-8 인코딩으로 JSON 파일을 엽니다.
        json.dump(
            subtitle_data, f, ensure_ascii=False, indent=4
        )  # 딕셔너리 데이터를 들여쓰기가 포함된 예쁜 JSON 포맷으로 저장합니다.
    df = pd.DataFrame(
        subtitle_data
    )  # Pandas를 활용해 수집된 데이터를 2차원 데이터프레임 구조로 변환합니다.
    df.to_csv(
        csv_path, index=False, encoding="utf-8-sig"
    )  # 엑셀 프로그램에서 한글이 깨지는 것을 막기 위해 UTF-8 BOM 인코딩으로 CSV를 저장합니다.
    with open(
        ass_path, "w", encoding="utf-8"
    ) as f:  # 자막 스타일링이 가능한 ASS 형식으로 파일을 엽니다.
        f.write(
            "[Script Info]\nTitle: Auto Generated by Whisper\nScriptType: v4.00+\n\n"
        )  # ASS 메타데이터 헤더 정보를 기록합니다.
        f.write(
            "[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
        )  # 자막 스타일 요소들의 규격을 선언합니다.
        f.write(
            "Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n\n"
        )  # 기본 Arial 폰트와 레이아웃 스타일을 정의합니다.
        f.write(
            "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
        )  # 자막 대사가 출력될 이벤트 행 구조를 정의합니다.
        for data in subtitle_data:  # 촘촘하게 쪼개진 자막 리스트를 순회하며 파일에 대사를 써내려갑니다.
            start_ass = format_ass_time(
                data["start_time"]
            )  # 시작 초 단위를 ASS 포맷 규격 문자열로 가공합니다.
            end_ass = format_ass_time(
                data["end_time"]
            )  # 종료 초 단위를 ASS 포맷 규격 문자열로 가공합니다.
            text_ass = data[
                "text"
            ]  # 가공할 문자열에서 순수 자막 텍스트만 추출합니다.
            f.write(
                f"Dialogue: 0,{start_ass},{end_ass},Default,,0,0,0,,{text_ass}\n"
            )  # 최종적으로 가공된 자막 행 데이터를 파일에 한 줄씩 출력합니다.
    print(
        "🎉 문장 쪼개기가 반영된 자막 저장이 완료되었습니다!"
    )  # 모든 작업이 성공적으로 끝났음을 알립니다.

# --- 함수 실행 예시 ---
# --- 함수 실행부 수정 예시 ---
VIDEO_FILE = "../data/p13_gross_motor_1.mp4"  # 원본 비디오 파일이 저장된 경로를 지정합니다.
OUTPUT_FOLDER = "../data/p13_gross_motor_1_ass"  # 자막 파일들이 저장될 폴더 경로를 지정합니다.

# 기존 model_size="base"를 고정밀 "turbo" 모델로 변경하여 함수를 호출합니다.
generate_short_subtitle_files(
    VIDEO_FILE, OUTPUT_FOLDER, model_size="turbo"
)  # 하이퍼파라미터가 적용된 고정밀 전사를 시작합니다.